model:
  path: bigscience/bloom-560m
  eos_token_id: 50256

tokenizer:
  path: bigscience/bloom-560m

dataset:
  path: the_pile

data_generator:
  api_start_character: "["
  api_end_character: "]"
  api_output_character: "→"

  top_k: 4
  sampling_threshold: 0.2
  filtering_threshold: 0.3

  max_new_tokens: 100

  n_api_pad: 100