model:
  path: bigscience/bloom-560m
  eos_token_id: 50256

tokenizer:
  path: bigscience/bloom-560m

dataset:
  path: the_pile

data_generator:
  api_start_character: "["
  api_end_character: "]"
  api_output_character: "→"
  sampling_threshold: 0.2
  filtering_threshold: 0.3